name: quoty_dumpling_app
version: 1.0.0+1
description: A new Flutter project.
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  provider: ^3.2.0
  gradient_nav_bar: ^1.0.0
  intl: ^0.16.0
  auto_size_text: ^2.1.0
  flutter_staggered_animations: ^0.1.2
  sqflite: ^1.2.0
  shared_preferences: ^0.5.6+1
  audioplayers: ^0.14.0
  flutter_phoenix: ^0.1.0
  url_launcher: ^5.4.1
  quiver: ^2.1.3
  flutter_staggered_grid_view: ^0.3.0
  device_preview: ^0.4.5
  flutter_screenutil: ^1.0.2
  tuple: ^1.0.3
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
dev_dependencies:
  icon_font_generator: ^1.0.0
  flutter_test:
    sdk: flutter
scripts:
  generate_icons: icon_font_generator
    --from=assets/svgs
    --class-name=CustomIcons
    --out-font=assets/icons/icons.ttf
    --out-flutter=lib/icons/custom_icons.dart
flutter:
  assets:
    - assets/images/
    - assets/quotes/
    - assets/items/
    - assets/achievements/
    - assets/sounds/
  fonts:
    -
      family: SofiaPro
      fonts:
        -
          asset: assets/fonts/SofiaProLight.ttf
        -
          asset: assets/fonts/SofiaProLight-Italic.ttf
          style: italic
        -
          asset: assets/fonts/SofiaProBold.ttf
          weight: 700
    -
      family: Pacifico
      fonts:
        -
          asset: assets/fonts/Pacifico-Regular.ttf
    -
      family: CustomIcons
      fonts:
        -
          asset: assets/icons/icons.ttf
  uses-material-design: true
