/// Flutter icons DumplingIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DumplingIcon
///      fonts:
///       - asset: fonts/DumplingIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kDumplingFam = 'DumplingIcon';

  static const IconData dumpling =
      const IconData(0xe801, fontFamily: _kDumplingFam);

  static const _kDiamondFam = 'DiamondIcon';

  static const IconData diamond =
      const IconData(0xe800, fontFamily: _kDiamondFam);
}
